# -*- mode: ruby -*-
# vi: set ft=ruby :

# require 'berkshelf/vagrant'

boxes = [
{ :name => :tomstack01, :ip => '33.33.33.10' },
]

Vagrant.configure("2") do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'opscode-ubuntu-14.04'
  config.vm.box_url = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box'
 
  # Enabling the Berkshelf plugin. To enable this globally, add this configuration
  # option to your ~/.vagrant.d/Vagrantfile file
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "../../../../Berksfile"
  config.omnibus.chef_version = :latest

  # elasticsearch needs more than Vagrant's default 312MB RAM on my machine
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
  end

  # Name and build each server
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.host_name =   "%s" % opts[:name].to_s
      config.vm.network :private_network, ip: opts[:ip]
   end
  end

  config.vm.provision :chef_solo do |chef|
    chef.run_list = [
      # wrapper cookbook for testing
      "recipe[tomstack_test_elasticsearch::test]"
    ]
  end
end
